name = "nvshitostore-catalog"
pages_build_output_dir = "."
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nvshitostore-db"
database_id = "a81dccc4-5f52-4080-b4c4-72a9411c355b"

[[r2_buckets]]
binding = "CATALOG_IMAGES"
bucket_name = "nvshitostore-images"